Translation:Guiding Participants,why_do_people_participate_in_open_source_communities
opensource-way-chinese-translation/the_open_source_way-guidebook-2.0-zh pull request #18
Opened 2021-10-26 14:02 UTC by WUTONK

修复了之前的错误pr

2021-11-02 21:49 UTC, Cubik65536 approved these changes
感觉还行， @LLLgoyour 来看看

2021-11-03 21:58 UTC, KevinZonda requested changes

2021-11-03 21:58 UTC, KevinZonda commented on translation/Guiding Participants/guiding_participants.md
> +"参与"一个开源项目是一个有趣的、有点抽象的描述概念。”我只是一个用户！不用跟我谈论更多“和”我应该怎么样才能为这个项目作出贡献“之间的分界线就很明了。某个人对项目的参与从他与软件的关系已经不仅仅是使用它时开始。而且由于开源软件本质上是包容性和参与性的，因此大多数**用户**也变成了某种**参与者**，通常通过在项目的博客上留下评论、在项目的反馈跟踪器中提交问题或在社交媒体上参与项目。通过使用开
Use Chinese symbols.
```suggestion
“参与”一个开源项目是一个有趣的、有点抽象的描述概念。“我只是一个用户！不用跟我谈论更多”和”我应该怎么样才能为这个项目作出贡献“之间的分界线就很明了。某个人对项目的参与从他与软件的关系已经不仅仅是使用它时开始。而且由于开源软件本质上是包容性和参与性的，因此大多数**用户**也变成了某种**参与者**，通常通过在项目的博客上留下评论、在项目的反馈跟踪器中提交问题或在社交媒体上参与项目。通过使用开源软件，他们**已经**开始参与让软件变得更好的过程。
```

in `开源软件本质上是包容性和参与性的`, it's grammar structure should be SVP instead SP.

`通常通过在项目的博客上留下评论` lacks subject.

2021-11-03 21:58 UTC, KevinZonda commented on translation/Guiding Participants/guiding_participants.md
> +- 推荐并提供帮助他人采用和使用本软件。
Why some of them hv period symbols, some hv not?

2021-11-03 21:58 UTC, KevinZonda commented on translation/Guiding Participants/guiding_participants.md
> +在以下情况下本节很适用：
It looks weird.

2021-11-03 21:58 UTC, KevinZonda commented on translation/Guiding Participants/guiding_participants.md
> +- 你希望建立一个桥梁来使参与者成为贡献者。
```suggestion
- 你希望建立一个来使参与者成为贡献者的桥梁。
```

2021-11-03 21:58 UTC, KevinZonda commented on translation/Guiding Participants/guiding_participants.md
> +- 你希望为您的参与社区提供更好的体验。
```suggestion
- 你希望为您参与的社区提供更好的体验。
```

2021-11-03 21:58 UTC, KevinZonda commented on translation/Guiding Participants/guiding_participants.md
> +- 你想了解由参与度较低的用户、热情的参与者或积极的贡献者组成的社区之间的差异
Why some of them hv period symbols, some hv not?

2021-11-03 21:58 UTC, KevinZonda commented on translation/Guiding Participants/why_do_people_participate_in_open_source_communities.md
> +如果这是一个人提供贡献的唯一原因，他们会因为自己的具体需要而在项目中留下。这可能是一个完美的结果，但它不是一条发展长期维护者的道路。
Please separate.

2021-11-03 21:59 UTC, KevinZonda commented
Thank you for your patient. Apologise to slow CR. Currently I am busier than usual and under extremely high pressure, it may take longer to response you. Apologise again for the inconvenience I caused. :)

2021-11-03 22:03 UTC, KevinZonda commented
Also, currently, I have no Chinese IME, which means I cannot provide complete Chinese suggestions, but I'll gv a correct direction which you can fix everything up. In other words, you hv to read every review carefully so that you won't miss anything. I hope I can review your corrected content soon. Wish you every success with your future contribution. :)

2021-11-04 04:29 UTC, LLLgoyour requested changes

2021-11-12 20:58 UTC, LLLgoyour approved these changes

2021-11-12 21:12 UTC, Cubik65536 commented
Thanks @LLLgoyour @WUTONK

2021-11-12 21:12 UTC, merged