Translation: Attracting Users/attracting_users.md
opensource-way-chinese-translation/the_open_source_way-guidebook-2.0-zh pull request #19
Opened 2021-11-12 14:40 UTC by Hsiao-Feng

2021-11-14 11:48 UTC, WUTONK commented
请勿重复翻译章节

2021-11-14 19:13 UTC, KevinZonda requested changes

2021-11-14 19:13 UTC, KevinZonda commented on translation/Attracting Users/attracting_users.md
> +本章就开源软件项目取得成功的切要之处给予重要、有所裨益、及时的建议。我们把这些建议写在此章，旨在帮助吸引用户，而非留住用户。因此，沟通和多元化的思想作为后续步骤。
“切要之处” 是什么？

2021-11-14 19:13 UTC, KevinZonda commented on translation/Attracting Users/attracting_users.md
> +- 你想要了解本指南的更多观点——吸引用户是建立贡献者社区的切要任务；
```suggestion
- 你想要了解本指南的更多观点——吸引用户是建立贡献者社区的主要任务；
```

2021-11-14 19:13 UTC, KevinZonda commented on translation/Attracting Users/attracting_users.md
> +- 你正在找一个开源项目的关键要素清单，无论是你想着手打造一个开源项目、研究一个项目可行性或是什么别的目的；
```suggestion
- 你正在寻求一个开源项目的关键要素清单，无论是你想着手打造一个开源项目、研究一个项目可行性或是什么其它的目的；
```

2021-11-14 19:13 UTC, KevinZonda commented on translation/Attracting Users/attracting_users.md
> +- 你正在找怎么让软件拥有更多用户的技巧；
```suggestion
- 你正在探寻怎么让软件拥有更多用户的技巧；
```

2021-11-14 19:13 UTC, KevinZonda commented on translation/Attracting Users/attracting_users.md
> +- 你已经读了前面的章节，并喜欢从头到尾读完一本书。
```suggestion
- 你已经阅读前面的章节，并喜欢从头到尾读完一本书。
```

2021-11-15 00:32 UTC, LLLgoyour requested changes

2021-11-15 00:32 UTC, LLLgoyour commented on translation/Attracting Users/attracting_users.md
> +- 你想要了解本指南的更多观点——吸引用户是建立贡献者社区的切要任务；
切要本身使用无错，意为要紧、重要。

2021-11-15 00:32 UTC, LLLgoyour commented on translation/Attracting Users/attracting_users.md
> +- 你正在找一个开源项目的关键要素清单，无论是你想着手打造一个开源项目、研究一个项目可行性或是什么别的目的；
你正在寻求一个开源项目的关键要素清单，无论是你想着手打造一个开源项目、研究一个项目可行性或是其它的某个目的；

2021-11-15 00:32 UTC, LLLgoyour commented on translation/Attracting Users/attracting_users.md
> +本指南认为，发展贡献者社区的方法是用户采纳。这里有一些言简意赅的原因。
本指南认为，发展贡献者社区的方法是采纳用户的建议。这里有一些言简意赅的原因。

2021-11-15 00:32 UTC, LLLgoyour commented on translation/Attracting Users/attracting_users.md
> +可以这么想想——人们第一次造访你的社区，看到社区有正式的行为准则和多元化的领导者面孔。有人会看到自己在社区中被代表着，有着身心的安全感。这会使他们第一次造访项目网站时，留下社区热情的印象。如果没有这些明显的文化元素，这些人会在考虑成为合作者和开发者之前放弃。
可以这么想想——人们第一次造访你的社区，看到社区有正式的行为准则和多元化的领导者面孔。有人会知道自己在社区中的位置，有着身心上的安全感。这会使他们第一次造访项目网站时，留下社区热情的印象。如果没有这些明显的文化元素，这些人会在考虑成为合作者和开发者之前放弃。

2021-11-15 00:32 UTC, LLLgoyour commented on translation/Attracting Users/attracting_users.md
> +本章就开源软件项目取得成功的切要之处给予重要、有所裨益、及时的建议。我们把这些建议写在此章，旨在帮助吸引用户，而非留住用户。因此，沟通和多元化的思想作为后续步骤。
意为要紧、重要。切要之处即重要、主要之处

2021-11-15 00:32 UTC, LLLgoyour commented on translation/Attracting Users/attracting_users.md
> +沟通和多元化也是一个项目的首要任务。向世界分享你的软件，告诉大家你的软件是做什么的、为什么要用你的软件——在这个过程中沟通是尤为重要的。在论坛中获取到用户的反馈也是很重要的。多样性和包容性是为创新、弹性和长期可持续发展做准备。如果你的社区不像这个世界，那它也不会长存于这个世界。
沟通和多元化也是一个项目的首要任务。向世界分享你的软件，告诉大家你的软件是做什么的、为什么要用你的软件——在这个过程中沟通是尤为重要的。在论坛中获取到用户的反馈也是很重要的。多样性和包容性是为创新、弹性和长期可持续发展做准备。如果你的社区与这个世界格格不入，那它也不会长存于这个世界。

2021-11-15 04:48 UTC, Hsiao-Feng commented on translation/Attracting Users/attracting_users.md
> +- 你想要了解本指南的更多观点——吸引用户是建立贡献者社区的切要任务；
> 
> 
> 切要本身使用无错，意为要紧、重要。

既然的确会引起疑问，改成更为常见的说法也好。

2021-11-19 05:50 UTC, LLLgoyour requested changes

2021-11-19 05:50 UTC, LLLgoyour commented on translation/Attracting Users/attracting_users.md
> +如果你满足其中之一，那么这章会对你很有用：
```suggestion
如果你满足以下其中之一，那么这章会对你很有用：
```

2021-11-20 19:21 UTC, LLLgoyour approved these changes

2021-11-22 23:33 UTC, Cubik65536 approved these changes

2021-11-22 23:33 UTC, merged

2021-11-24 19:58 UTC, KevinZonda reviewed
好屌！