Translation: The Shape of Things
opensource-way-chinese-translation/the_open_source_way-guidebook-2.0-zh pull request #22
Opened 2021-11-15 01:26 UTC by KevinZonda

2021-11-15 04:24 UTC, LLLgoyour requested changes

2021-11-15 04:24 UTC, LLLgoyour commented on translation/Presenting the Open Source Way/the_shape_of_things.md
> +当你看到本指南的目录时，应该能注意到组织的流程：从用户到参与者到参与者到贡献者。这种安排特别追踪了我们对一个社区如何产生和发展的看法。而这一切都始于一个需求。如果你在开源项目和社区工作过，你可能已经多次看到这个循环。它是这样的：
```suggestion
当你看到本指南的目录时，应该能注意到一个有组织的流程：从用户到参与者，到参与者再到贡献者。这种流程特别追踪了我们对一个社区产生和发展过程的看法，而这一切都始于一个需求。如果你在开源项目和社区工作过，你可能已经多次看到这个循环。就像这些：
```

2021-11-15 04:24 UTC, LLLgoyour commented on translation/Presenting the Open Source Way/the_shape_of_things.md
> +因此，一个项目的主要和持续的重点是 _照顾好你的用户_，因为他们中的一些人将成为你的贡献者，你希望他们这样做是出于爱而不是怨恨。
```suggestion
因此，一个项目的主要和持续的重点是 _多关照你的用户_，因为他们中的一些人将成为你的贡献者，你希望他们这样做是出于爱而不是怨恨。
```

2021-11-15 04:24 UTC, LLLgoyour commented on translation/Presenting the Open Source Way/the_shape_of_things.md
> +当你降低参与的障碍时，你就会使你的项目在各个层面都受到欢迎。但是这并不意味着你要 _消除所有的障碍_ ——只是适当地降低大部分的障碍。例如，对于接受系统钥匙的人来说，适当的障碍是必要的，这些障碍与只允许某些参与者为配置管理系统贡献帮助文章或补丁的障碍是不同的。
```suggestion
当你降低参与的障碍时，你就会使你的项目在各个层面都受到欢迎。但是这并不意味着你要 _消除所有的障碍_ ——只是适当地降低大部分的障碍。例如，对于修补配置管理系统的人来说，适当的障碍是必要的，为此设置的障碍与为贡献帮助文章设置的障碍是不同的。
```

2021-11-15 04:24 UTC, LLLgoyour commented on translation/Presenting the Open Source Way/the_shape_of_things.md
> +思考一下这条道路：让人们知道你伟大的舞蹈派对是一件事。让这些舞者有能力倡导你举办舞蹈派对是另一回事。让舞蹈派对能够发展到欢迎来自我们周围世界的各种形式的音乐和舞蹈，这是一件非常伟大的事情。
```suggestion
用这个情景思考一下：向人们宣传你盛大的舞蹈派对很重要。让这些舞者有能力倡导你举办舞蹈派对是另一回事。能让舞蹈派对能够融合来自我们周围世界的各种形式的音乐和舞蹈是一件非常伟大的事情。
```

2021-11-15 04:24 UTC, LLLgoyour commented on translation/Presenting the Open Source Way/the_shape_of_things.md
> +要让看到你的海报并出现的舞者坚持下去是第一步，如果他们能马上看到这是一个适合他们和他们的地方，那就会很有帮助。
```suggestion
要让看到你舞会的海报并参与的舞者坚持下去是第一步。如果他们能马上看到这是一个适合他们和他们朋友的地方，这歌宣传就会很有帮助。
```

2021-11-15 04:24 UTC, LLLgoyour commented on translation/Presenting the Open Source Way/the_shape_of_things.md
> +我们想更深入地传达所有这些信息的最佳方式是通过故事。除了本章正文中自然出现的故事外，指南和 The Open Source Way 社区中还有其他区域可以收集所有这些原因的故事。
```suggestion
我们想通过讲述故事来更深入地传达所有这些信息的最佳方式。除了本章正文中自然出现的故事外，指南和开源之路（The Open Source Way）社区中还有其他区域可以收集所有这些原因的故事。
```

2021-11-15 05:50 UTC, LLLgoyour requested changes

2021-11-15 05:50 UTC, LLLgoyour commented on translation/Presenting the Open Source Way/the_shape_of_things.md
> +我们想通过讲述故事来更深入地传达所有这些信息的最佳方式。除了本章正文中自然出现的故事外，指南和开源之路（The Open Source Way）社区中还有其他区域可以收集所有这些原因的故事。
```suggestion
我们想通过讲述故事来更深入地传达所有这些信息的最佳方式。除了本章正文中自然出现的故事外，指南和开源之路（The Open Source Way）社区中还有其他区域可以收集所有问题解答的故事。
```

2021-11-16 16:15 UTC, LLLgoyour approved these changes

2021-11-17 03:38 UTC, Cubik65536 approved these changes
当原文内容被移除之后本PR将会被merge

2021-11-17 03:38 UTC, Cubik65536 commented on translation/Presenting the Open Source Way/the_shape_of_things.md
>  comes about and grows. And it all starts with a need. If you’ve worked in open source projects and
这里是没有把原文清理干净吗？

2021-11-17 18:15 UTC, KevinZonda commented
/cc @Cubik65536

2021-11-17 18:29 UTC, merged