Translation: what_is_a_contribution.md
opensource-way-chinese-translation/the_open_source_way-guidebook-2.0-zh pull request #23
Opened 2021-11-15 07:06 UTC by WUTONK

2021-11-17 18:46 UTC, Cubik65536 commented
Is it **ready for review**??

2021-11-19 01:45 UTC, LLLgoyour requested changes

2021-11-19 01:45 UTC, LLLgoyour commented on translation/Growing Contributors/what_is_a_contribution.md
> +有一种常见的误解，认为只有代码或是文档才是对开源项目的“真正”贡献。这个可怕的想法有一个名字——“代码为王”。
```suggestion
有一种常见的误解，认为只有代码和可能编写的其开发文档才是对开源项目的“真正”贡献。这个可怕的想法有一个在历史上铭记的名字——“代码为王（code is king)”。
```

2021-11-19 01:45 UTC, LLLgoyour commented on translation/Growing Contributors/what_is_a_contribution.md
> +但事实上，除了这两种方式，还有更多的其他贡献方式。这对于项目和这些作出贡献的形形色色的群体来说也带来了成倍的价值
```suggestion
但事实上，除了这两种方式，还有更多的其他贡献方式。更多的贡献方式也给项目和这些作出贡献的形形色色的群体带来了成倍的价值。
```

2021-11-19 01:45 UTC, LLLgoyour commented on translation/Growing Contributors/what_is_a_contribution.md
> +贡献就是在开源社区的许可下，免费提供给该社区的任何原创的、有意的、实质性的对象。贡献可以来自个人或是社区。
```suggestion
贡献就是在开源社区的许可下，免费提供给该社区的任何原创的、有目的性的、实在的对象。贡献可以来自个人或是社区。
```

2021-11-19 01:45 UTC, LLLgoyour commented on translation/Growing Contributors/what_is_a_contribution.md
> +开源贡献者即为参与对社区做出贡献的任何个人。社区本质上是一种人际关系。他们由人组成，而不是机构。但机构也可以派遣其成员、员工、领导等作为贡献者为社区做出贡献
```suggestion
开源贡献者即为参与对社区做出贡献的任何个人。社区本质上是一种人际关系。他们由人组成，而不是机构。但机构也可以派遣其成员、员工、领导等作为贡献者为社区做出贡献。
```

2021-11-19 01:45 UTC, LLLgoyour commented on translation/Growing Contributors/what_is_a_contribution.md
> +- 代码，只要是指示机器执行操作的内容，与类型无关。
```suggestion
- 代码。与类型无关，只要是能让机器执行的内容。
```

2021-11-19 01:45 UTC, LLLgoyour commented on translation/Growing Contributors/what_is_a_contribution.md
> +- 物理材料，如服务器或贡献者礼物。
```suggestion
-实物材料，如服务器或者任何贡献的礼物。
```

2021-11-19 01:45 UTC, LLLgoyour commented on translation/Growing Contributors/what_is_a_contribution.md
> +- 金钱，在可能的情况下。(但这并不总是一个容易，甚至是可行的贡献给许多开源项目的一种方式)。
```suggestion
- 金钱，在可能的情况下欢迎。但如果是许多开源项目，这并不总是一种可能或是能容易做到的贡献方式。
```

2021-11-19 01:45 UTC, LLLgoyour commented on translation/Growing Contributors/what_is_a_contribution.md
> +- 作为论坛的主持人。
```suggestion
- 作为论坛的版主。
```

2021-11-19 01:45 UTC, LLLgoyour commented on translation/Growing Contributors/what_is_a_contribution.md
> +- 在活动中帮忙
```suggestion
- 在活动中提供帮助
```

2021-11-19 01:45 UTC, LLLgoyour commented on translation/Growing Contributors/what_is_a_contribution.md
> +- 作为发布管理者。
```suggestion
- 担任发布版本的管理者。
```

2021-11-19 01:45 UTC, LLLgoyour commented on translation/Growing Contributors/what_is_a_contribution.md
> +- 一个网站设计。
```suggestion
- 做一个网站设计。
```

2021-11-19 01:45 UTC, LLLgoyour commented on translation/Growing Contributors/what_is_a_contribution.md
> +- 在法律方面帮助项目。
```suggestion
- 为项目提供法律方面的建议。
```

2021-11-19 01:45 UTC, LLLgoyour commented on translation/Growing Contributors/what_is_a_contribution.md
> +- 构建贡献者/维护者/领导者招聘流程。
```suggestion
- 构建贡献者/维护者/领导者招新流程。
```

2021-11-19 01:45 UTC, LLLgoyour commented on translation/Growing Contributors/what_is_a_contribution.md
> +实际上，从客户服务到产品管理，你在工作中可能学到的任何技能都可以作为你做出贡献的基础。任何你能想象到的其他社区所需的需求，都可能是开源社区的共同需求。
```suggestion
实际上，从客户服务到产品管理，你在工作中可能学到的任何技能都是你做出贡献的基础。你能想到的任何其他社区所需的需求，都可能是一个开源社区的需求；这也是一种贡献的基础。
```

2021-11-19 01:45 UTC, LLLgoyour commented on translation/Growing Contributors/what_is_a_contribution.md
> +实际上，从客户服务到产品管理，你在工作中可能学到的任何技能都可以作为你做出贡献的基础。任何你能想象到的其他社区所需的需求，都可能是开源社区的共同需求。
哪里翻译出来的共同..？

2021-11-19 01:45 UTC, LLLgoyour commented on translation/Growing Contributors/what_is_a_contribution.md
> +注意各种贡献的广度和深度是有益的。作为社区管理实践的一部分，你必须意识到人们对一个项目的多种贡献方式。你可以感谢他们的贡献，将他们的行动从个人连接到整体，并做出更大的作用。
```suggestion
注意各种有广度和有深度的贡献都是有益的。作为社区管理实践的一部分，你必须意识到人们对一个项目的多种贡献方式。然后从个人到整体，你可以感谢大家一起做出的努力。
```

2021-11-19 02:20 UTC, Cubik65536 commented
@LLLgoyour 对不起按错了

2021-11-19 02:28 UTC, Cubik65536 requested changes
清理原文并不难，对吗

2021-11-19 02:28 UTC, Cubik65536 commented on translation/Growing Contributors/what_is_a_contribution.md
>  In truth, there are exponentially more ways to contribute than just those two ways. And
多余的内容删掉

2021-11-19 02:28 UTC, Cubik65536 commented on translation/Growing Contributors/what_is_a_contribution.md
>  Practically any skill you might learn in a job role, from customer service to product management,
???

2021-11-19 02:28 UTC, Cubik65536 commented on translation/Growing Contributors/what_is_a_contribution.md
>  It is useful to be mindful of the breadth and depth of types of contributions. As part of the practice
???

2021-11-19 02:28 UTC, Cubik65536 commented on translation/Growing Contributors/what_is_a_contribution.md
>  - Monetary, where possible and welcome. (This is not always an easy or even possible way to
???

2021-11-19 02:28 UTC, Cubik65536 commented on translation/Growing Contributors/what_is_a_contribution.md
> +- 金钱，在可能的情况下。(这并不总是一个容易的，甚至是可行的贡献给许多开源项目的一种方式)。
``` suggestion
+ 在可能的情况下，金钱。（这并不是一个容易的，有时候甚至是可行的，给许多开源项目贡献的方式）
```

2021-11-19 02:32 UTC, WUTONK commented on translation/Growing Contributors/what_is_a_contribution.md
> +实际上，从客户服务到产品管理，你在工作中可能学到的任何技能都可以作为你做出贡献的基础。任何你能想象到的其他社区所需的需求，都可能是开源社区的共同需求。
意译，原本是“你在工作中可能学到的任何技能都可以作为你做出贡献的基础。你能想到的任何其他社区所需的需求，都可能是一个开源社区的需求；这也是一种贡献的基础。”但是感觉怪怪的，就加上了共同

2021-11-19 02:36 UTC, Cubik65536 commented on translation/Growing Contributors/what_is_a_contribution.md
> +实际上，从客户服务到产品管理，你在工作中可能学到的任何技能都可以作为你做出贡献的基础。任何你能想象到的其他社区所需的需求，都可能是开源社区的共同需求。
@WUTONK 

> 不要自己加戏

这不是我第一次说这句话了吧

2021-11-19 02:38 UTC, Cubik65536 commented on translation/Growing Contributors/what_is_a_contribution.md
> +- 金钱，在可能的情况下。(但这并不总是一个容易，甚至是可行的贡献给许多开源项目的一种方式)。
```suggestion
- 在可能的情况下，金钱。（这并不是一个容易的，有时候甚至是可行的，给许多开源项目贡献的方式）
```

2021-11-19 18:26 UTC, LLLgoyour approved these changes

2021-11-19 18:45 UTC, Cubik65536 approved these changes

2021-11-19 18:46 UTC, merged