translation: Onboarding.md
opensource-way-chinese-translation/the_open_source_way-guidebook-2.0-zh pull request #24
Opened 2021-11-15 10:33 UTC by WUTONK

2021-11-19 20:26 UTC, Cubik65536 requested changes
先正确排版markdown，两行文字之间应该空一行而非两行

2021-11-20 04:08 UTC, LLLgoyour requested changes

2021-11-20 04:08 UTC, LLLgoyour commented on translation/Growing Contributors/onboarding.md
> +因此，任何希望长期持续发展的开源项目都应该认真考虑它与新贡献者的联系、迎接和适应的方式。一句话，他们是如何 "上岗"的。一个精心设计的入职过程会使参与者更容易为项目做出贡献，并使贡献者能够尽快对工作产生积极影响。
```suggestion
因此，任何希望长期持续发展的开源项目都应该认真考虑它与新贡献者的联系、迎接和适应的方式。一句话，他们是如何 "上岗"的。一个精心设计的入职经历会使参与者更容易为项目做出贡献，并使贡献者能够尽快对工作产生积极影响。
```

2021-11-20 04:08 UTC, LLLgoyour commented on translation/Growing Contributors/onboarding.md
> +在这一章中，我们将讨论你的社区的入职过程的重要性，并研究一些常见的入职资源和做法，这可能有助于你的项目变得更加可持续。
```suggestion
在这一章中，我们将讨论你的社区的入职经历的重要性，并研究一些常见的入职资源和做法，这可能有助于你的项目变得更加可持续。
```

2021-11-20 04:08 UTC, LLLgoyour commented on translation/Growing Contributors/onboarding.md
> +当你努力使你的项目的入职过程和体验最有效时，问问自己这些问题：
```suggestion
当你努力使你的项目的入职经历最有效果时，问问自己这些问题：
```

2021-11-20 04:08 UTC, LLLgoyour commented on translation/Growing Contributors/onboarding.md
> +回答关于你的项目入职过程的第一个问题需要做大量的工作。新来的贡献者需要知道什么是他们可以做出的最有用的贡献。相当多的项目在他们的源代码库中设置了 "首次贡献者" 或类似的标签，这是引导新来的贡献者去解决问题和错误的一个很好的方法，同时也向新人介绍了项目的原始资料。
```suggestion
回答关于你的项目入职经历的第一个问题需要做大量的工作。新来的贡献者需要知道什么是他们可以做出的最有用的贡献。相当多的项目在他们的源代码库中设置了 "首次贡献者" 或类似的标签，这是引导新来的贡献者去解决问题和错误的一个很好的方法，同时也向新人介绍了项目的原始资料。
```

2021-11-20 04:08 UTC, LLLgoyour commented on translation/Growing Contributors/onboarding.md
> +当人们加入一个新的社区时，他们可能会发现在交流渠道（如邮件或Slack）上的讨论让人不知所措。为了减轻他们的困惑或压力，可以考虑在这些频道中,为新的社区成员创造空间，让他们在开始和适应的时候使用。诸如 "入门 "或 "介绍 "这样的专用频道可以成为为人们提供安全感的地方，以便新成员提问。这些频道也允许更多有经验的社区成员通过帮助回答新用户的问题，甚至只是提供鼓励来协助入职。这对使新的社区成员在开
```suggestion
当人们加入一个新的社区时，他们可能会发现在交流渠道（如邮件或Slack）上的讨论让人不知所措。为了减轻他们的困惑或压力，可以考虑在这些频道中，为新的社区成员创造空间，让他们在开始和适应的时候使用。诸如 "入门 "或 "介绍 "这样的专用频道可以成为为人们提供安全感的地方，以便新成员提问。这些频道也允许更多有经验的社区成员通过帮助回答新用户的问题，甚至只是提供鼓励来协助入职。这对使新的社区成员在开始时感到受欢迎有很大的帮助。
```

2021-11-20 04:08 UTC, LLLgoyour commented on translation/Growing Contributors/onboarding.md
> +第三个问题是“如何贡献”的问题。有的项目经常公布源代码，来使其易于发现。。。对的，就只是这样。你可能听说过其他人把这种方法称为“把它扔到墙上（throwing it over the wall）”，但这不是一个人们倾向于礼貌地使用的词语。太多的项目会将其代码或内容直接推到公共场所，宣布对所有人开放，然后想知道所有可能的贡献者都在哪里。这可能是因为在项目中缺乏获得贡献的文件和程序，且存在真正的加入
```suggestion
第三个问题是“如何贡献”的问题。有的项目经常公布源代码，让人能容易发现这个项目。对，就是如此。你可能听说过其他人把这种方法称为“把它扔到墙上（throwing it over the wall）”，但这不是一个人们倾向于礼貌地使用的词语。太多的项目会将其代码或内容直接推到公共场所，宣布对所有人开放，然后想知道所有可能的贡献者都在哪里。这可能是因为在项目中缺乏获得贡献的文件和程序，且存在真正的加入障碍。
```

2021-11-20 04:08 UTC, LLLgoyour commented on translation/Growing Contributors/onboarding.md
> +如果你的预算允许，你可以组织正式的迎新会，作为一个 "day 0" 活动，或者在午餐时间组织迎新会，让新成员认识其他社区成员，这样他们就知道以后可以向谁提问了。
```suggestion
如果你的预算允许，你可以组织正式的迎新会，作为一个“day 0”活动，或者在午餐时间组织迎新会，让新成员认识其他社区成员，这样他们就知道以后可以向谁提问了。
```

2021-11-24 20:03 UTC, KevinZonda requested changes

2021-11-24 20:03 UTC, KevinZonda commented on translation/Growing Contributors/onboarding.md
> +在许多方面，在一个新的开源社区中的入职经历与你在一份新工作中的体验非常相似。
```suggestion
在许多方面，一个新的开源社区中的入职经历与你在一份新工作中的体验非常相似。
```

2021-11-24 20:03 UTC, KevinZonda commented on translation/Growing Contributors/onboarding.md
> +但是，你也可能加入一个有着广泛历史的团队--存在共同的规范和习俗、内部笑话、行话、不言而喻的协议、共同的纽带和集体认同感。简而言之，你的新团队或组织会有一种在你加入之前就存在的文化。这种文化的各个方面在很大程度上是无形的，但它们会大大影响你与他人合作的能力。一个有效的入职体验能让你了解这种文化。
```suggestion
但是，你也可能加入一个有着广泛历史的团队——存在共同的规范和习俗、内部笑话、行话、不言而喻的协议、共同的纽带和集体认同感。简而言之，你的新团队或组织会有一种在你加入之前就存在的文化。这种文化的各个方面在很大程度上是无形的，但它们会大大影响你与他人合作的能力。一个有效的入职体验能让你了解这种文化。
```

中文标点

2021-11-24 20:03 UTC, KevinZonda commented on translation/Growing Contributors/onboarding.md
>  ```
@Cubik65536 能帮助确认一下这里是代码符号吗？我认为这里可能是引用或者其他的。Thx

2021-11-24 20:03 UTC, KevinZonda commented on translation/Growing Contributors/onboarding.md
>  ```
同上 @Cubik65536

2021-11-24 20:03 UTC, KevinZonda commented on translation/Growing Contributors/onboarding.md
> +当你努力使你的项目的入职经历和体验最有效时，问问自己这些问题：
Sigh...

2021-11-24 20:03 UTC, KevinZonda commented on translation/Growing Contributors/onboarding.md
> +第二个问题--关于 "在哪里贡献"————这是一个并不像你想象的那样在项目里会经常提出的问题。一些项目老手可能会不屑一顾地说，"你需要的东西在论坛上" 或 "如果你需要更多的细节，请去阅读wiki"。但是，在哪个具体的资源库里有这些材料？在什么组织下？还有其他类似的项目呢？确保你的项目网站有明确的链接，让新的贡献者能够对项目产生影响。这些链接也不应该被埋没；如果可能的话，它们应该就在主页上。
```suggestion
第二个问题——关于 "在哪里贡献"——这是一个并不像你想象的那样在项目里会经常提出的问题。一些项目老手可能会不屑一顾地说，"你需要的东西在论坛上" 或 "如果你需要更多的细节，请去阅读wiki"。但是，在哪个具体的资源库里有这些材料？在什么组织下？还有其他类似的项目呢？确保你的项目网站有明确的链接，让新的贡献者能够对项目产生影响。这些链接也不应该被埋没；如果可能的话，它们应该就在主页上。
```

你确定不修正一下符号。PS，这个suggestion不包含对引号的修正。

2021-11-24 20:04 UTC, KevinZonda commented
我合体推荐你直接commit我们给你提供的suggestion。

2021-11-25 00:49 UTC, LLLgoyour approved these changes
等 @Cubik65536 确认 @KevinZonda 提出的问题后默认批准。

2021-11-25 02:52 UTC, Cubik65536 commented on translation/Growing Contributors/onboarding.md
>  ```
@KevinZonda 没有明白你想问的事情，原文这里确实是粗体字

2021-11-25 02:56 UTC, Cubik65536 commented
@WUTONK 标点符号全部自己检查一遍，谢谢。

2021-11-25 03:30 UTC, Cubik65536 commented
@WUTONK 另外，L21到L36的代码块

<pre><code>
```
xxx
xxx
xxx
```
</code></pre>

全部都是引用

<pre><code>
> xxx
> xxx
> xxx
</code></pre>

------

感谢 @KevinZonda 的提醒

2023-02-01 19:34 UTC, closed without merging